In [1]:
import pandas as pd

In [2]:
dict1 = {'Name':['Priyang','Aadhya','krishna','Vedant','Parshv','Mittal','Archana'],
'Marks':[98,89,99,87,90,83,99],
'Gender':['Male','Female','Female','Male','Male','Female','Female']
}

df1 = pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2  krishna     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

# 1.Display Top 3 Rows of the Dataset

In [3]:
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2  krishna     99  Female

# 2.Check Last 3 Rows of trhe DataSet

In [4]:
df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

# 3.Find Shape of Our Dataset(Number of Rows & Number of Columns)

In [8]:
print(df1.shape[0])
print(df1.shape[1])

7
3

# 4. Get Information About our Dataset Like Total Number Rows, Total Number of Columns,Datatypes of each column and Memory Requirement

In [9]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 300.0 bytes

# 5.Check Null values in the Dataset

In [12]:
df1.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

# 6.Get Overall Statistics About the DataFrame

In [14]:
df1.describe(include='all')

           Name      Marks  Gender
count         7   7.000000       7
unique        7        NaN       2
top     Priyang        NaN  Female
freq          1        NaN       4
mean        NaN  92.142857     NaN
std         NaN   6.491753     NaN
min         NaN  83.000000     NaN
25%         NaN  88.000000     NaN
50%         NaN  90.000000     NaN
75%         NaN  98.500000     NaN
max         NaN  99.000000     NaN

# 7.Find Unique values From The Gender Column

In [15]:
df1['Gender'].unique()

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

# 8.Find the Number of Unique Values from the Gender Column

In [16]:
df1['Gender'].nunique()

2

# 9.Display Count of Unique Values in Gender Column

In [17]:
df1['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

# 10.Find Total Number of Students Having Marks Between 90 to 100 (Inclusive) using between method

In [20]:
df1[df1['Marks'] >= 90]

      Name  Marks  Gender
0  Priyang     98    Male
2  krishna     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [24]:
len(df1[(df1['Marks']>=90) & (df1['Marks']<=100)])

4

In [25]:
sum(df1['Marks'].between(90,100))

4

# 11.Find Average Marks

In [28]:
df1['Marks'].mean()

np.float64(92.14285714285714)

# 12. Apply Method

In [29]:
def Marks(x):
    return x/2

In [31]:
df1['Half_marks']=df1['Marks'].apply(Marks)
df1

      Name  Marks  Gender  Half_marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2  krishna     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

In [35]:
df1['Marks'].apply(lambda x:x/2)

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Marks, dtype: float64

# 13.MAP function

In [36]:
df1['Gender'].map({'Male':1,'Female':0})

0    1
1    0
2    0
3    1
4    1
5    0
6    0
Name: Gender, dtype: int64

# 14. Drop The Columns

In [38]:
df1.drop('Half_marks',axis=1)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2  krishna     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

# 15.Print The Name of The Columns

In [39]:
df1.columns

Index(['Name', 'Marks', 'Gender', 'Half_marks'], dtype='str')

In [40]:
df1.index

RangeIndex(start=0, stop=7, step=1)

# 17. Sort The DataFrame As Per The Marks Column

In [41]:
df1.sort_values(by='Marks')

      Name  Marks  Gender  Half_marks
5   Mittal     83  Female        41.5
3   Vedant     87    Male        43.5
1   Aadhya     89  Female        44.5
4   Parshv     90    Male        45.0
0  Priyang     98    Male        49.0
2  krishna     99  Female        49.5
6  Archana     99  Female        49.5

In [43]:
df1.sort_values(by=['Marks','Gender'],ascending=False)

      Name  Marks  Gender  Half_marks
2  krishna     99  Female        49.5
6  Archana     99  Female        49.5
0  Priyang     98    Male        49.0
4   Parshv     90    Male        45.0
1   Aadhya     89  Female        44.5
3   Vedant     87    Male        43.5
5   Mittal     83  Female        41.5

# 17.Display Name & Marks of the Female Students Only

In [45]:
df1[df1['Gender']=='Female'][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2  krishna     99
5   Mittal     83
6  Archana     99

In [47]:
df1[df1['Gender'].isin(['Female'])][['Name','Marks']]

      Name  Marks
1   Aadhya     89
2  krishna     99
5   Mittal     83
6  Archana     99